include: [".well-known"]
theme: minima
title: perzarys' page
description: Bookmark this to keep an eye on my project updates!
author: perzarys
email: "E-Mail me at perzarys@mailbox.org or write me on Matrix via @perzarys:matrix.org"